import { opportunities as mockOpportunities } from '../mockData';
import { useLiveData } from '../useLiveData';

function ScoreBar({ score }) {
  const color = score >= 85 ? '#16a34a' : score >= 70 ? '#3B7DD8' : '#f59e0b';
  return (
    <div className="flex items-center gap-2">
      <div className="flex-1 h-2 bg-gray-100 rounded-full overflow-hidden">
        <div
          className="h-full rounded-full"
          style={{ width: `${score}%`, backgroundColor: color, transition: 'width 0.4s ease' }}
        />
      </div>
      <span
        className="text-xs font-bold w-6 text-right"
        style={{ color }}
      >
        {score}
      </span>
    </div>
  );
}

export default function AIInsights() {
  const { data: insightData, source: insightSource } = useLiveData('/api/ai-insights', { insights: mockOpportunities }, 60 * 60 * 1000);

  // Normalise live vs mock shape
  const opportunities = (insightData?.insights ?? mockOpportunities).map((item, i) => ({
    id:           item.id          ?? i,
    company:      item.company,
    subSector:    item.subSector   ?? item.sub_sector ?? '',
    score:        item.score,
    thesis:       item.thesis,
    keyDrivers:   item.keyDrivers  ?? item.drivers    ?? [],
    ev:           item.ev          ?? mockOpportunities[i]?.ev          ?? 'N/A',
    revenue:      item.revenue     ?? mockOpportunities[i]?.revenue     ?? 'N/A',
    ebitdaMargin: item.ebitdaMargin ?? mockOpportunities[i]?.ebitdaMargin ?? 'N/A',
    entryMultiple:item.entryMultiple ?? mockOpportunities[i]?.entryMultiple ?? 'N/A',
  }));

  const topOpps = opportunities.slice(0, 5);

  return (
    <div>
      <div className="mb-6">
        <div className="flex items-center gap-3">
          <h2 className="text-lg font-semibold text-gray-900">AI Insights</h2>
          <span
            className="text-xs px-2 py-0.5 rounded-full font-medium text-white"
            style={{ backgroundColor: '#3B7DD8' }}
          >
            AI-Generated
          </span>
        </div>
        <p className="text-sm text-gray-500 mt-0.5">
          {insightSource === 'live'
            ? 'Opportunity scores generated by Claude · refreshes hourly'
            : 'Opportunity pipeline ranked by AI Opportunity Score — add ANTHROPIC_API_KEY to go live'}
        </p>
      </div>

      {/* Summary strip */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {[
          { label: 'Companies Screened', value: '847', sub: 'This quarter' },
          { label: 'Active Opportunities', value: '7', sub: 'Score ≥ 65' },
          { label: 'Avg. Opportunity Score', value: '80', sub: 'Top 5 targets' },
          { label: 'Estimated Deployable Capital', value: '$6.1B', sub: 'Pipeline value' },
        ].map((stat) => (
          <div key={stat.label} className="bg-white rounded-lg border border-gray-200 p-4">
            <div className="text-xs text-gray-500">{stat.label}</div>
            <div className="text-2xl font-bold text-gray-900 mt-1">{stat.value}</div>
            <div className="text-xs text-gray-400 mt-0.5">{stat.sub}</div>
          </div>
        ))}
      </div>

      {/* Opportunity pipeline table */}
      <div className="bg-white rounded-lg border border-gray-200 overflow-hidden mb-6">
        <div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between">
          <h3 className="text-sm font-semibold text-gray-800">Opportunity Pipeline</h3>
          <button className="text-xs font-medium hover:underline" style={{ color: '#3B7DD8' }}>
            View all →
          </button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100">
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">Company</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide hidden md:table-cell">Sub-Sector</th>
                <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide w-40">Opportunity Score</th>
                <th className="text-right px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide hidden lg:table-cell">Est. EV</th>
                <th className="text-right px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide hidden lg:table-cell">Revenue</th>
                <th className="text-right px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide hidden lg:table-cell">Entry Multiple</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {opportunities.map((opp) => (
                <tr key={opp.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-5 py-4 font-semibold text-gray-900">{opp.company}</td>
                  <td className="px-5 py-4 text-gray-500 hidden md:table-cell text-xs">{opp.subSector}</td>
                  <td className="px-5 py-4 w-40">
                    <ScoreBar score={opp.score} />
                  </td>
                  <td className="px-5 py-4 text-right text-gray-800 font-medium hidden lg:table-cell">{opp.ev}</td>
                  <td className="px-5 py-4 text-right text-gray-600 hidden lg:table-cell">{opp.revenue}</td>
                  <td className="px-5 py-4 text-right text-gray-600 hidden lg:table-cell text-xs">{opp.entryMultiple}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Opportunity detail cards */}
      <div className="space-y-4">
        <h3 className="text-sm font-semibold text-gray-700 uppercase tracking-wide">
          Top Opportunities — Investment Theses
        </h3>
        {topOpps.map((opp) => {
          const scoreColor = opp.score >= 85 ? '#16a34a' : opp.score >= 70 ? '#3B7DD8' : '#f59e0b';
          return (
            <div key={opp.id} className="bg-white rounded-lg border border-gray-200 p-5">
              <div className="flex items-start justify-between gap-4 mb-3">
                <div className="flex-1">
                  <div className="flex items-center gap-3 flex-wrap">
                    <h4 className="text-base font-semibold text-gray-900">{opp.company}</h4>
                    <span className="text-xs px-2 py-0.5 rounded bg-gray-100 text-gray-600">{opp.subSector}</span>
                  </div>
                  <div className="flex items-center gap-4 mt-1 text-xs text-gray-500 flex-wrap">
                    <span>EV: <strong className="text-gray-700">{opp.ev}</strong></span>
                    <span>Revenue: <strong className="text-gray-700">{opp.revenue}</strong></span>
                    <span>EBITDA Margin: <strong className="text-gray-700">{opp.ebitdaMargin}</strong></span>
                    <span>Entry: <strong className="text-gray-700">{opp.entryMultiple}</strong></span>
                  </div>
                </div>
                <div className="flex-shrink-0 text-center">
                  <div
                    className="w-12 h-12 rounded-full flex items-center justify-center text-white font-bold text-sm border-2"
                    style={{ borderColor: scoreColor, color: scoreColor, backgroundColor: `${scoreColor}15` }}
                  >
                    {opp.score}
                  </div>
                  <div className="text-xs text-gray-400 mt-0.5">Score</div>
                </div>
              </div>

              <p className="text-sm text-gray-700 leading-relaxed mb-3">{opp.thesis}</p>

              <div className="flex flex-wrap gap-2">
                {opp.keyDrivers.map((driver) => (
                  <span
                    key={driver}
                    className="text-xs px-2.5 py-1 rounded-full border font-medium"
                    style={{ borderColor: '#3B7DD8', color: '#3B7DD8', backgroundColor: 'rgba(59,125,216,0.06)' }}
                  >
                    {driver}
                  </span>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
