// ─── KPI Bar ────────────────────────────────────────────────────────────────
export const kpiData = {
  marketMomentumScore: 74,
  newTransactions90d: 38,
  capitalRaised90d: '$4.2B',
  distressAlerts: 3,
  exitEvents: 7,
  aiOpportunityScore: 82,
  momentumTrend: [62, 65, 61, 68, 70, 67, 72, 74, 71, 75, 73, 74],
};

// ─── Transactions ────────────────────────────────────────────────────────────
export const transactions = [
  {
    id: 1,
    date: '2025-11-14',
    target: 'Kellanova',
    buyer: 'Mars, Inc.',
    type: 'Acquisition',
    evAmount: '$35.9B',
    sector: 'Snacks',
    status: 'Closed',
  },
  {
    id: 2,
    date: '2025-10-22',
    target: 'Liquid I.V.',
    buyer: 'Unilever',
    type: 'Acquisition',
    evAmount: '$700M',
    sector: 'Beverages',
    status: 'Closed',
  },
  {
    id: 3,
    date: '2025-10-08',
    target: 'Vital Proteins',
    buyer: 'Nestlé',
    type: 'Acquisition',
    evAmount: '$690M',
    sector: 'Supplements',
    status: 'Closed',
  },
  {
    id: 4,
    date: '2025-09-30',
    target: 'Chobani',
    buyer: 'Lactalis Group',
    type: 'Acquisition',
    evAmount: '$3.2B',
    sector: 'Dairy',
    status: 'Pending',
  },
  {
    id: 5,
    date: '2025-09-18',
    target: 'Daily Harvest',
    buyer: 'Wonder Group',
    type: 'Acquisition',
    evAmount: '$275M',
    sector: 'Frozen Food',
    status: 'Closed',
  },
  {
    id: 6,
    date: '2025-09-05',
    target: 'Poppi',
    buyer: 'PepsiCo',
    type: 'Acquisition',
    evAmount: '$1.95B',
    sector: 'Beverages',
    status: 'Closed',
  },
  {
    id: 7,
    date: '2025-08-27',
    target: 'Chomps',
    buyer: 'General Mills',
    type: 'Minority Stake',
    evAmount: '$185M',
    sector: 'Snacks',
    status: 'Closed',
  },
  {
    id: 8,
    date: '2025-08-15',
    target: 'Kevin\'s Natural Foods',
    buyer: 'TPG Capital',
    type: 'Growth Equity',
    evAmount: '$120M',
    sector: 'Frozen Food',
    status: 'Closed',
  },
  {
    id: 9,
    date: '2025-08-03',
    target: 'Maple Leaf Foods (Consumer Div.)',
    buyer: 'Advent International',
    type: 'Buyout',
    evAmount: '$2.4B',
    sector: 'Protein',
    status: 'Rumored',
  },
  {
    id: 10,
    date: '2025-07-22',
    target: 'Tessemae\'s',
    buyer: 'Butterfly Equity',
    type: 'Growth Equity',
    evAmount: '$65M',
    sector: 'Condiments',
    status: 'Closed',
  },
  {
    id: 11,
    date: '2025-07-10',
    target: 'SunOpta (Oat Milk Div.)',
    buyer: 'Undisclosed PE',
    type: 'Carve-out',
    evAmount: '$310M',
    sector: 'Plant-Based',
    status: 'Rumored',
  },
  {
    id: 12,
    date: '2025-06-28',
    target: 'FreshRealm',
    buyer: 'KKR',
    type: 'Distressed Sale',
    evAmount: '$145M',
    sector: 'Meal Kits',
    status: 'Closed',
  },
  {
    id: 13,
    date: '2025-06-15',
    target: 'Olipop',
    buyer: 'Strategic Investors',
    type: 'Series D',
    evAmount: '$250M',
    sector: 'Beverages',
    status: 'Closed',
  },
  {
    id: 14,
    date: '2025-06-01',
    target: 'Nature\'s Bakery',
    buyer: 'TreeHouse Foods',
    type: 'Acquisition',
    evAmount: '$420M',
    sector: 'Snacks',
    status: 'Closed',
  },
  {
    id: 15,
    date: '2025-05-20',
    target: 'Siete Foods',
    buyer: 'PepsiCo',
    type: 'Acquisition',
    evAmount: '$1.2B',
    sector: 'Snacks',
    status: 'Closed',
  },
];

// ─── News ────────────────────────────────────────────────────────────────────
export const news = [
  {
    id: 1,
    date: '2025-11-15',
    headline: 'FDA Proposes Revised "Healthy" Labeling Standards',
    summary:
      'New FDA guidelines require front-of-pack nutrition labels on all processed foods by 2026. Brands with high sodium or saturated fat face reformulation pressure. Estimated $2B+ compliance cost across industry.',
    source: 'FDA / Reuters',
    tag: 'Regulatory',
    urgent: false,
  },
  {
    id: 2,
    date: '2025-11-13',
    headline: 'PepsiCo Misses Q3 Revenue Estimates by 4%; Volumes Decline 2%',
    summary:
      'PepsiCo reported Q3 net revenue of $22.3B vs. $23.2B consensus. Snacks volume fell 2% YoY amid consumer trade-down. Guidance cut for full year — mgmt flagging macro headwinds in North America.',
    source: 'PepsiCo IR / Bloomberg',
    tag: 'Earnings',
    urgent: true,
  },
  {
    id: 3,
    date: '2025-11-10',
    headline: 'Corn Futures Hit 18-Month High on USDA Supply Shock Report',
    summary:
      'USDA revised US corn production down 6% due to Midwest drought. Corn futures up 14% month-over-month. Downstream impact expected for sweetener costs, animal feed, and ethanol. Snack and cereal margins at risk.',
    source: 'USDA / CME Group',
    tag: 'Commodity',
    urgent: true,
  },
  {
    id: 4,
    date: '2025-11-08',
    headline: 'GLP-1 Drug Penetration Reaches 9% of US Adults — Food Categories Bifurcating',
    summary:
      'New KFF Health survey shows 9% of US adults now use GLP-1 medications, up from 6% last year. High-protein, low-calorie formats accelerating; indulgent snack categories seeing softness. PE firms pivoting portfolios toward functional nutrition.',
    source: 'KFF / Euromonitor',
    tag: 'Consumer Trends',
    urgent: false,
  },
  {
    id: 5,
    date: '2025-11-05',
    headline: 'Plant-Based Meat Category Contracts 11% YoY; Beyond Meat Reports Going-Concern Warning',
    summary:
      'Plant-based meat dollar sales down 11% in tracked channels per NielsenIQ. Beyond Meat issued going-concern language in 10-Q filing. Category contracting creates distressed M&A opportunities. Refrigerated formats outperforming frozen.',
    source: 'NielsenIQ / SEC Filing',
    tag: 'Distress',
    urgent: true,
  },
  {
    id: 6,
    date: '2025-11-01',
    headline: 'Prebiotic/Probiotic Beverage Segment Posts 67% Growth in Convenience Channel',
    summary:
      'Functional beverages — led by prebiotic sodas and kefir — grew 67% in convenience stores per SPINS data. Poppi, Olipop, and Lifeway driving category. Distribution gaps persist in club and mass channels — white space for consolidators.',
    source: 'SPINS Data',
    tag: 'Growth',
    urgent: false,
  },
];

// ─── Distress & Exit Monitor ──────────────────────────────────────────────────
export const distressItems = [
  {
    id: 1,
    company: 'FreshRealm',
    type: 'Distress',
    signal: 'High Leverage',
    detail: 'Net Debt/EBITDA of 8.4x; covenant breach likely in Q1. Entered sale process.',
    severity: 'high',
    date: '2025-11-10',
  },
  {
    id: 2,
    company: 'B&G Foods',
    type: 'Distress',
    signal: 'Margin Pressure',
    detail: 'Gross margins compressed 320bps YoY. $1.1B debt load on declining volumes. Dividend cut expected.',
    severity: 'high',
    date: '2025-11-08',
  },
  {
    id: 3,
    company: 'SunOpta',
    type: 'Distress',
    signal: 'Liquidity Risk',
    detail: 'Oat milk segment operating losses widening. Revolver draw-down 85%. Strategic review announced.',
    severity: 'medium',
    date: '2025-11-05',
  },
  {
    id: 4,
    company: 'TreeHouse Foods',
    type: 'Watch',
    signal: 'Volume Declines',
    detail: 'Private label volumes off 4% as branded pricing normalizes. Integration costs from Nature\'s Bakery deal elevated.',
    severity: 'medium',
    date: '2025-10-30',
  },
];

export const exitItems = [
  {
    id: 1,
    company: 'Chomps',
    sponsor: 'Strand Equity',
    exitType: 'Strategic Sale',
    buyer: 'General Mills',
    moic: '6.2x',
    irr: '41%',
    date: '2025-08-27',
  },
  {
    id: 2,
    company: 'Poppi',
    sponsor: 'CAVU Consumer Partners',
    exitType: 'Strategic Sale',
    buyer: 'PepsiCo',
    moic: '11.4x',
    irr: '68%',
    date: '2025-09-06',
  },
  {
    id: 3,
    company: 'Siete Foods',
    sponsor: 'None (Founder-led)',
    exitType: 'Strategic Sale',
    buyer: 'PepsiCo',
    moic: 'N/A',
    irr: 'N/A',
    date: '2025-05-20',
  },
  {
    id: 4,
    company: 'Daily Harvest',
    sponsor: 'Lightspeed / GV',
    exitType: 'Strategic Sale',
    buyer: 'Wonder Group',
    moic: '1.3x',
    irr: '8%',
    date: '2025-09-18',
  },
  {
    id: 5,
    company: 'Kevin\'s Natural Foods',
    sponsor: 'L Catterton',
    exitType: 'Partial Exit',
    buyer: 'TPG Capital',
    moic: '3.1x',
    irr: '28%',
    date: '2025-08-15',
  },
];

// ─── Consumer Trends ─────────────────────────────────────────────────────────
export const searchTrends = [
  { category: 'High Protein Snacks', index: 94, change1yr: '+38%', momentum: 'up' },
  { category: 'Prebiotic Soda', index: 87, change1yr: '+112%', momentum: 'up' },
  { category: 'GLP-1 Friendly Foods', index: 82, change1yr: '+340%', momentum: 'up' },
  { category: 'Oat Milk', index: 71, change1yr: '-8%', momentum: 'down' },
  { category: 'Functional Beverages', index: 78, change1yr: '+54%', momentum: 'up' },
  { category: 'Grass-Fed Beef', index: 65, change1yr: '+19%', momentum: 'up' },
  { category: 'Plant-Based Meat', index: 42, change1yr: '-29%', momentum: 'down' },
  { category: 'Keto Snacks', index: 55, change1yr: '-14%', momentum: 'down' },
  { category: 'Freeze-Dried Meals', index: 61, change1yr: '+22%', momentum: 'up' },
  { category: 'Collagen Peptides', index: 69, change1yr: '+31%', momentum: 'up' },
  { category: 'Adaptogen Drinks', index: 74, change1yr: '+87%', momentum: 'up' },
  { category: 'Air-Fried Snacks', index: 58, change1yr: '+11%', momentum: 'up' },
];

export const socialBuzz = [
  {
    topic: '#HighProtein',
    platform: 'TikTok / Instagram',
    volume7d: '4.2M',
    change: '+18%',
    topContent: 'Protein ice cream, cottage cheese recipes',
    momentum: 'up',
  },
  {
    topic: '#PrebioticSoda',
    platform: 'TikTok',
    volume7d: '2.8M',
    change: '+94%',
    topContent: 'Poppi & Olipop taste tests, DIY recipes',
    momentum: 'up',
  },
  {
    topic: '#GLP1Diet',
    platform: 'TikTok / Reddit',
    volume7d: '6.1M',
    change: '+210%',
    topContent: 'Ozempic food lists, satiety hacks',
    momentum: 'up',
  },
  {
    topic: '#FunctionalFood',
    platform: 'Instagram',
    volume7d: '1.9M',
    change: '+42%',
    topContent: 'Mushroom coffee, nootropic snacks',
    momentum: 'up',
  },
  {
    topic: '#OatMilk',
    platform: 'Instagram / Pinterest',
    volume7d: '1.1M',
    change: '-12%',
    topContent: 'Latte art, barista comparisons',
    momentum: 'down',
  },
  {
    topic: '#BeyondMeat',
    platform: 'Twitter / Reddit',
    volume7d: '780K',
    change: '-31%',
    topContent: 'Negative sentiment, brand boycotts',
    momentum: 'down',
  },
  {
    topic: '#CollagenPeptides',
    platform: 'TikTok',
    volume7d: '1.4M',
    change: '+27%',
    topContent: 'Skin/joint health, coffee additions',
    momentum: 'up',
  },
  {
    topic: '#CleanLabel',
    platform: 'Instagram',
    volume7d: '2.3M',
    change: '+33%',
    topContent: 'Ingredient list checks, brand callouts',
    momentum: 'up',
  },
];

// ─── Commodity Prices ─────────────────────────────────────────────────────────
export const commodities = [
  {
    name: 'Corn',
    unit: '$/bushel',
    price: 5.82,
    change30d: '+14.2%',
    changeYoY: '+22.8%',
    trend30d: 'up',
    trendYoY: 'up',
    lastUpdated: '2025-11-15',
  },
  {
    name: 'Milk (Class III)',
    unit: '$/cwt',
    price: 18.45,
    change30d: '+3.1%',
    changeYoY: '-6.4%',
    trend30d: 'up',
    trendYoY: 'down',
    lastUpdated: '2025-11-15',
  },
  {
    name: 'Raw Sugar (#11)',
    unit: 'cents/lb',
    price: 22.8,
    change30d: '-2.4%',
    changeYoY: '+8.1%',
    trend30d: 'down',
    trendYoY: 'up',
    lastUpdated: '2025-11-15',
  },
  {
    name: 'Soybean Oil',
    unit: 'cents/lb',
    price: 48.3,
    change30d: '+6.7%',
    changeYoY: '+18.2%',
    trend30d: 'up',
    trendYoY: 'up',
    lastUpdated: '2025-11-15',
  },
  {
    name: 'Wheat (SRW)',
    unit: '$/bushel',
    price: 6.14,
    change30d: '-1.8%',
    changeYoY: '-4.9%',
    trend30d: 'down',
    trendYoY: 'down',
    lastUpdated: '2025-11-15',
  },
  {
    name: 'Coffee (Arabica)',
    unit: 'cents/lb',
    price: 198.4,
    change30d: '+8.3%',
    changeYoY: '+41.6%',
    trend30d: 'up',
    trendYoY: 'up',
    lastUpdated: '2025-11-15',
  },
  {
    name: 'Cocoa',
    unit: '$/MT',
    price: 8420,
    change30d: '-4.1%',
    changeYoY: '+127.3%',
    trend30d: 'down',
    trendYoY: 'up',
    lastUpdated: '2025-11-15',
  },
  {
    name: 'Lean Hogs',
    unit: 'cents/lb',
    price: 74.6,
    change30d: '+2.8%',
    changeYoY: '+11.4%',
    trend30d: 'up',
    trendYoY: 'up',
    lastUpdated: '2025-11-15',
  },
];

// ─── AI Insights / Opportunity Pipeline ──────────────────────────────────────
export const opportunities = [
  {
    id: 1,
    company: 'Maple Leaf Foods (Consumer Div.)',
    subSector: 'Packaged Protein',
    score: 91,
    thesis:
      'Leading Canadian protein brand with strong US distribution runway. Parent exploring consumer division carve-out at attractive 8x EBITDA vs. 12-14x peer set. GLP-1 tailwind for high-protein positioning. Platform for protein consolidation.',
    keyDrivers: ['Category tailwind', 'Carve-out discount', 'US expansion', 'Protein consolidation platform'],
    ev: '~$2.4B',
    revenue: '$1.8B',
    ebitdaMargin: '11%',
    entryMultiple: '8x EV/EBITDA',
  },
  {
    id: 2,
    company: 'Chomps',
    subSector: 'Better-for-You Snacks',
    score: 88,
    thesis:
      'Fastest-growing meat snack brand with 70%+ e-commerce sales. Clean label (no additives) resonates with GLP-1 consumer. $200M revenue run-rate. Strand Equity exploring full exit to strategic. Mars/Hershey most likely buyers.',
    keyDrivers: ['E-commerce leader', 'Clean label', 'GLP-1 aligned', 'Auction process ongoing'],
    ev: '~$800M',
    revenue: '$200M',
    ebitdaMargin: '22%',
    entryMultiple: '~4x EV/Revenue',
  },
  {
    id: 3,
    company: 'Kevin\'s Natural Foods',
    subSector: 'Frozen / Refrigerated Meals',
    score: 84,
    thesis:
      'Premium clean-label meal brand growing 45% YoY. New TPG investment provides runway for retail expansion. Underpenetrated in club and mass channels. Potential roll-up vehicle for better-for-you meals. CEO recently upgraded.',
    keyDrivers: ['45% YoY growth', 'Club/mass white space', 'Clean label', 'TPG growth capital'],
    ev: '$350M',
    revenue: '$95M',
    ebitdaMargin: '14%',
    entryMultiple: '3.7x EV/Revenue',
  },
  {
    id: 4,
    company: 'Poppi',
    subSector: 'Functional Beverages',
    score: 82,
    thesis:
      'Prebiotic soda category creator with PepsiCo distribution backing post-acquisition. Category growing 100%+. Watch for potential bolt-on targets in functional soda (e.g., Olipop). Comp for valuing next-gen beverage platforms.',
    keyDrivers: ['Category creation', 'PepsiCo distribution', '100%+ category growth', 'Valuation comp'],
    ev: '$1.95B',
    revenue: '$115M',
    ebitdaMargin: 'NM',
    entryMultiple: '17x EV/Revenue',
  },
  {
    id: 5,
    company: 'Tessemae\'s',
    subSector: 'Condiments / Dressings',
    score: 79,
    thesis:
      'Organic, clean-label condiment leader. Butterfly Equity growth investment accelerating retail and foodservice. $65M revenue growing 25% YoY. Fragmented category ripe for roll-up. Attractive entry multiple at ~2x revenue.',
    keyDrivers: ['Organic/clean label', '25% revenue growth', 'Foodservice expansion', '2x EV/Rev entry'],
    ev: '$130M',
    revenue: '$65M',
    ebitdaMargin: '9%',
    entryMultiple: '2x EV/Revenue',
  },
  {
    id: 6,
    company: 'Lil Bucks',
    subSector: 'Specialty / Superfood Snacks',
    score: 71,
    thesis:
      'Emerging buckwheat-based snack brand with strong DTC and specialty retail presence. First-mover in grain-free grain category. Pre-Series A — high risk, high upside. Consider for venture/growth mandate.',
    keyDrivers: ['Novel ingredient', 'DTC flywheel', 'Pre-institutional', 'Clean label'],
    ev: '$35M',
    revenue: '$8M',
    ebitdaMargin: 'NM',
    entryMultiple: '4.4x EV/Revenue',
  },
  {
    id: 7,
    company: 'Soylent',
    subSector: 'Functional Nutrition',
    score: 65,
    thesis:
      'Complete nutrition brand with loyal DTC subscriber base. Revenue declining after peak hype cycle but profitability improving. GLP-1 tailwind for meal replacement positioning. Opportunistic entry at sub-1x revenue.',
    keyDrivers: ['DTC subscriptions', 'Margin improvement', 'GLP-1 adjacent', 'Distressed valuation'],
    ev: '$90M',
    revenue: '$110M',
    ebitdaMargin: '4%',
    entryMultiple: '0.8x EV/Revenue',
  },
];

// ─── Watchlists ───────────────────────────────────────────────────────────────
export const watchlists = {
  platformTargets: {
    label: 'Platform Targets',
    count: 23,
    newThisWeek: 3,
    companies: [
      { name: 'Maple Leaf Foods (Consumer)', sector: 'Packaged Protein', addedDate: '2025-11-10' },
      { name: 'Utz Brands', sector: 'Salty Snacks', addedDate: '2025-11-08' },
      { name: 'Farmer\'s Business Network (Food Div.)', sector: 'AgTech / Food', addedDate: '2025-11-05' },
      { name: 'Enjoy Life Foods', sector: 'Allergen-Free Snacks', addedDate: '2025-10-28' },
      { name: 'Califia Farms', sector: 'Plant-Based Beverages', addedDate: '2025-10-22' },
      { name: 'Kodiak Cakes', sector: 'Breakfast / Protein', addedDate: '2025-10-15' },
      { name: 'Dave\'s Killer Bread', sector: 'Bread / Baked Goods', addedDate: '2025-10-10' },
    ],
  },
  addonTargets: {
    label: 'Add-on Targets',
    count: 15,
    newThisWeek: 2,
    companies: [
      { name: 'Chomps', sector: 'Meat Snacks', addedDate: '2025-11-12' },
      { name: 'Lil Bucks', sector: 'Superfood Snacks', addedDate: '2025-11-09' },
      { name: 'Kevin\'s Natural Foods', sector: 'Frozen Meals', addedDate: '2025-11-01' },
      { name: 'Tessemae\'s', sector: 'Condiments', addedDate: '2025-10-25' },
      { name: 'Once Upon a Farm', sector: 'Baby Food', addedDate: '2025-10-18' },
      { name: 'Brami Snacks', sector: 'Lupini / Protein Snacks', addedDate: '2025-10-12' },
      { name: 'Pulp Pantry', sector: 'Upcycled Snacks', addedDate: '2025-10-05' },
    ],
  },
  distressWatch: {
    label: 'Distress Watch',
    count: 8,
    newThisWeek: 1,
    companies: [
      { name: 'FreshRealm', sector: 'Meal Kits', addedDate: '2025-11-10' },
      { name: 'B&G Foods', sector: 'Center Store', addedDate: '2025-11-08' },
      { name: 'SunOpta (Oat Milk)', sector: 'Plant-Based', addedDate: '2025-11-05' },
      { name: 'Beyond Meat', sector: 'Plant-Based Protein', addedDate: '2025-11-01' },
      { name: 'Tattooed Chef', sector: 'Frozen Plant-Based', addedDate: '2025-10-20' },
      { name: 'Farmer\'s Fridge', sector: 'Fresh Vending', addedDate: '2025-10-14' },
      { name: 'Good Catch Foods', sector: 'Plant-Based Seafood', addedDate: '2025-10-05' },
    ],
  },
  newThisWeek: {
    label: 'New This Week',
    count: 12,
    newThisWeek: 12,
    companies: [
      { name: 'Farmer\'s Business Network (Food Div.)', sector: 'AgTech', addedDate: '2025-11-15' },
      { name: 'Utz Brands', sector: 'Salty Snacks', addedDate: '2025-11-14' },
      { name: 'Chomps', sector: 'Meat Snacks', addedDate: '2025-11-13' },
      { name: 'Farmer\'s Fridge', sector: 'Fresh Vending', addedDate: '2025-11-13' },
      { name: 'Lil Bucks', sector: 'Superfood Snacks', addedDate: '2025-11-12' },
      { name: 'B&G Foods', sector: 'Center Store', addedDate: '2025-11-11' },
      { name: 'Califia Farms', sector: 'Plant-Based Beverages', addedDate: '2025-11-11' },
    ],
  },
};
